
name: Build it!
on: [push, pull_request]
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - uses: actions/setup-python@v2
              with:
                python-version: '3.7'
                cache: 'pip'
            - name: Build bag for sample CODEX dataset
              run: |
                pip install -r requirements.txt
                bash ./test.sh
