name: Basic test
on: [push, pull_request]
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: '3.7' 
    architecture: 'x64'
- name: "Running basic test with sample CODEX dataset"
- run: bash ./test.sh
